version: '3.8'

services:
  oracle-db:
    image: gvenzl/oracle-xe:11.2.0.2
    container_name: oracle-db
    ports:
      - "49161:49161"
    environment:
      ORACLE_PASSWORD: oracle
      APP_USER: system
      APP_USER_PASSWORD: oracle
    volumes:
      - oracle-data:/opt/oracle/oradata

  comercio-api:
    build: .
    container_name: comercio-api
    depends_on:
      - oracle-db
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:oracle:thin:@oracle-db:49161/XE
      SPRING_DATASOURCE_USERNAME: system
      SPRING_DATASOURCE_PASSWORD: oracle
    networks:
      - comercio-net

volumes:
  oracle-data:

networks:
  comercio-net:
